### ISSUE TITLE
pip install fails - missing README.md

### ISSUE THREAD

**Issue by ifrguy** [silascutler/LnkParse#2]
G> pip3 install lnkfile
Downloading/unpacking lnkfile
  Downloading lnkfile-0.2.1.tar.gz
  Running setup.py (path:/var/tmp/pip_build_meg/lnkfile/setup.py) egg_info for package lnkfile
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/var/tmp/pip_build_meg/lnkfile/setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/var/tmp/pip_build_meg/lnkfile/setup.py", line 3, in <module>

    with open("README.md", "r") as fh:

FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /var/tmp/pip_build_meg/lnkfile
Storing debug log for failure in /tmp/tmpl77umvdb

**Comment by silascutler** [comment]
Thanks.  Right now - this is only written for 2.7  I'll work on migrating to python3
